services:
  - type: web
    name: invofer_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://sofia:fNQrMUoEZclc7hgEneLiUHItt2GiyRfT@dpg-cv4suvd6l47c73ar924g-a/invofer_prueba
      - key: SECRET_KEY
        value: django-insecure-1e*e#0+(9@7w)kz$8#r1p^=8r8m00hh)5esht7z2^2a2#mfebf
      - key: DEBUG
        value: "False"