# Generated by Django 5.0.7 on 2025-03-03 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_producto_categoria_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto_marca_categoria'),
        ),
    ]
