# Generated by Django 5.1.5 on 2025-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_presentacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
